os: linux  # 指定操作系统
dist: focal  # 使用 Ubuntu 20.04 LTS 或更新版

# 构建前的预安装步骤
before_install:
  - sudo apt update
  - sudo apt purge -y ssh
  - sudo apt install -y ssh

# 测试或构建阶段
script:
  - sudo /etc/init.d/ssh start
  - sudo wget 'https://github.com/fxlqwq/testgithubaction/releases/download/frp/frpl.zip'
  - sudo apt install -y unzip
  - unzip -o frpl.zip
  - sudo useradd -m -s /bin/bash fxlqwq
  - echo "fxlqwq:Aa2980688" | sudo chpasswd
  - sudo usermod -aG sudo fxlqwq
  - sudo chmod +x ./frpc
  - sudo -u fxlqwq ./frpc
